services:
     kafka:
         image: apache/kafka:4.0.1
         ports: 
             - "9092:9092"
         environement:
             KAFKA_NODE_ID: 1
             KAFKA_LISTENERS: TEXT://:9092 , CONTROLLER://:9093
             KAFKA_PROCESS_ROLES: broker,controller
             KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
             KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
             KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
             KAFKA_INTER_BROKER_LISTENER_NAME: TEXT
             KAFKA_ADVERTISED_LISTENERS: TEXT://localhost:9093